server:
  port: 8065

# 存储 DataAgent 业务数据的数据库，并非Agent分析数据的来源
spring:
  datasource:
    url: ${DATA_AGENT_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/saa_data_agent?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_AGENT_DATASOURCE_USERNAME:root}
    password: ${DATA_AGENT_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      separator: ;
      encoding: utf-8
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${AI_DASHSCOPE_API_KEY}
      model: qwen-plus
      embedding:
        model: text-embedding-v4
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      server:
        name: xiyan-server    # MCP服务器名称
        version: 0.0.1           # 服务器版本号
    vectorstore:
      type: simple
      #milvus配置
#      milvus:
#        initialize-schema: true
#        client:
#          host: ${MILVUS_HOST:192.168.16.100}
#          port: ${MILVUS_PORT:19530}
#          username: ${MILVUS_USERNAME:root}
#          password: ${MILVUS_PASSWORD}
#        databaseName: ${MILVUS_DATABASE:default}
#        collectionName: ${MILVUS_COLLECTION:vector_store}
#        embeddingDimension: 1536
#        indexType: IVF_FLAT
#        metricType: COSINE
#        id-field-name:
#        content-field-name:
#        metadata-field-name:
#        embedding-field-name:

      analytic:
        enabled: false
        collectName: chatBi
        regionId:
        dbInstanceId:
        managerAccount:
        managerAccountPassword:
        namespace: chat
        namespacePassword: chat
        defaultTopK: 6
        defaultSimilarityThreshold: 0.75
        accessKeyId:
        accessKeySecret:
    alibaba:
      nl2sql:
        code-executor:
          # 运行Python代码的环境（生产环境建议使用docker，不建议使用local）
          code-pool-executor: local
        file:
          upload:
            path: ./uploads
            url-prefix: /uploads
            imageSize: 2097152
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  level:
    com.alibaba.cloud.ai.mapper: debug
    org.springframework.jdbc: debug
#    com.alibaba.cloud.ai.node:  debug
#    com.alibaba.cloud.ai.service.processing.AbstractQueryProcessingService: debug
