#Copyright 2024-2025 the original author or authors.
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

# 运行后端应用
FROM openjdk:17-jdk-slim

WORKDIR /app

# 安装所需的软件
RUN apt update && apt install -y maven git python3

# 下载DataAgent源码，用于构建
RUN git clone https://github.com/spring-ai-alibaba/DataAgent.git \
    && cd DataAgent && mvn install -DskipTests \
    && cp ./data-agent-management/target/spring-ai-alibaba-data-agent-management-0.1.0-SNAPSHOT.jar /app/app.jar \
    && cd ..

# 创建配置文件目录
RUN mkdir -p /app/config

EXPOSE 8065

# 启动命令，优先使用外部配置文件
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=classpath:application.yml,optional:file:/app/config/application.yml"]
